services:
  app:
    build:
      context: .
      target: app
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PASSWORD=
    depends_on:
      - db
    volumes:
      - storage_data:/var/www/html/storage
    networks:
      - laravel

  web:
    build:
      context: .
      target: web
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: e-learning
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  storage_data:
  dbdata:
